#!/bin/sh

xrandr --output DP1 --auto --right-of eDP1
setxkbmap -layout us,ca -variant ,fr
setxkbmap -option 'grp:rctrl_rshift_toggle'
xmodmap ~/.xmodmap

~/.config/polybar/launch.sh

killall compton
feh --randomize --bg-fill ~/Pictures/Wallpapers/*
compton --config ~/Projects/dotfiles/compton.conf -b
