# Shell variables
# Generated by 'wal'
wallpaper='/home/parasithe/Pictures/Wallpapers/RAW_2016_06_20_22_02_16_154.jpg'

# Special
background='#0E0D15'
foreground='#B5B4C1'
cursor='#B5B4C1'

# Colors
color0='#0E0D15'
color1='#453B49'
color2='#38436C'
color3='#554F62'
color4='#9C614B'
color5='#A48778'
color6='#5A628C'
color7='#B5B4C1'
color8='#666666'
color9='#453B49'
color10='#38436C'
color11='#554F62'
color12='#9C614B'
color13='#A48778'
color14='#5A628C'
color15='#B5B4C1'
